### ISSUE TITLE
Card not showing up in Lovelace HA 2020.12.0

### ISSUE THREAD

**Issue by Ortep** [chaptergy/lightalarm-card#9] opened 2021-01-09 10:51 UTC
I used this card for quite a while. 
Now I started my HA fresh on new hardware. 
From that moment on I couldn't get the card to show up in Lovelace.

I added al the required entities and sensors.
I tried using the install 'button'. 
I tried also the manual install.

I did refresh the browser and also rebooted HA.

**Comment by chaptergy** [comment] 2021-01-09 11:46
Unfortunately I am not able to reproduce your issue. Have you tried updating to the newest Homeassistant version 2021.1? Could you also provide me with your configuration yaml for the card?  
Does nothing show up or is there an error? Have you clicked on "add to lovelace" in HACS?

**Comment by Ortep** [comment] 2021-01-09 15:25
Hi, I am running the latest version of HA 2021.1 since today. Still no luck.
Someone else to install to test it and he also did not succeed.
There are no errors, simply no card shows up in Lovelace.

I do not see "add to lovelace" in HACS. I used install.

When I go to: Configuration->Lovelace Dashboards->Resources
I see: /hacsfiles/lightalarm-card/lightalarm-card.js
The resource type is: Java module.

My configuration Yaml is:

input_datetime:
  lightalarm_time:
    name: Alarm Time
    has_date: false
    has_time: true

input_number:
  lightalarm_duration:
    name: Alarm Duration
    unit_of_measurement: min
    min: 0
    max: 60
    step: 1

input_select:
  lightalarm_options:
    name: Alarm Mode
    icon: mdi:alarm-plus
    options:
      - "Off"
      - "Workdays When Present"
      - "Workdays"
      - "Once Only"
      - "Every Day"
sensor:
  - platform: time_date
    display_options:
      - "time"





Op za 9 jan. 2021 om 12:47 schreef chaptergy <notifications@github.com>:

**Comment by chaptergy** [comment] 2021-01-17 17:58
Unfortunately I am not able to reproduce your issue. Maybe you are expecting the card to show up in the list of cards when adding a new card? Because unfortunately Home Assistant does not allow that, you'll have to select 'manual' and use the YAML editor first. Put `type: 'custom:lightalarm-card'`, and then you will be able to click on "show visual editor".

**Comment by Ortep** [comment] 2021-01-18 09:32
I just checked again.
I did used the Add Manual end typed the 'custom:lightalarm-card' as
requested.
Then I get an error telling me that a time entity is unknown.
The show visual editor is greyed out and not selectable.
I tried this with MS Edge and Google Chrome on my laptop and desktop.
BUT when I tried it on my Pixel 5 phone it was possible to select the
visual editor. After filling in the request information everything worked.
I could also edit the new card with Edge and Chrome on laptop/desktop. I
could not add another version. That is only possible with my phone.

Weird, but it is working for now.

Op zo 17 jan. 2021 om 18:58 schreef chaptergy <notifications@github.com>:

**Comment by chaptergy** [comment] 2021-01-18 10:46
Ah, please verify that it actually says `Error: Custom element not found: lightalarm-card`. I have noticed sometimes it lags behind and just ignores some letters at the end. If it says something like `Error: Custom element not found: lightalarm-car` with no `d` at the end. However this is unfortunately out of my control and has to do with the implementation in the home assistant frontend. If this is the issue you noticed, please go ahead and open an issue over in the [Home Assistant Frontend Repo](https://github.com/home-assistant/frontend)

**Comment by Ortep** [comment] 2021-01-18 13:17
Yes that is what I see.
Now you told it is 'lagging' I tried to be fast enough to click on the
"show code editor" field.
That actually works.


Op ma 18 jan. 2021 om 11:46 schreef chaptergy <notifications@github.com>:

**Comment by chaptergy** [comment] 2021-01-18 15:13
Allright, thanks for reporting. Unfortunately there is nothing I can do about that, since this is an issue with home assistant. I'll close this issue.

**Closed as completed by chaptergy** 2021-01-18 15:13 UTC

**Comment by chaptergy** [comment] 2021-01-18 21:46
A small additional note: It seems Home Assistant now finally supports custom cards on the list of all cards and it is now documented how to do this. I have added the functionality to this module in v3.0.3.
